project/urls.py
from django.conf.urls import url ,include
from project import views
from rest_framework import routers

# from project.views import ProjectMembersListView
#application namespace
app_name = 'ns-project'



urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.

    # The home page
    url(r'^$', views.index, name='index'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^add-sheet/$', views.AddSheet, name='add-sheet'),
    # test rest api
    url(r'^rest-api/$', views.RestApi, name='rest-api'),
    url(r'^api-sheets/(?P<status>.+)/(?P<empid>.+)/$', views.SheetsStatusViewSet.as_view(), name='user'),
    ###
    url(r'^sheet/(?P<pk>\d+)/edit/$', views.EditSheet, name='edit-sheet'),
    url(r'^sheet/(?P<pk>\d+)/submit/$', views.SubmitSheet, name='submit-sheet'),
    url(r'^sheet/(?P<pk>\d+)/change/$', views.ChangeStatus, name='change-status'),
    url(r'^my_sheet/$', views.MySheet, name='my-sheet'),
    # url(r'^all_sheets/$', views.ManagerPage, name='all-sheets'),
    url(r'^all_employees_sheets/$', views.AllSheets, name='emps-sheets'),
    url(r'^all_dept_sheet/$', views.AllDept, name='dept-sheets'),
    url(r'^all_dept_sheets/$', views.AllDepts, name='department-sheets'),
    url(r'^dept_no_sheets/$', views.DeptsnoSheets, name='department-nosheets'),
    #url(r'^all_emp/$', views.IsManager, name='all-emp'),
    url(r'^sheet/(?P<deptcode>\d+)/dept/$', views.DeptSheet, name='dept-sheet'),
    # Employees does'nt have task
    url(r'^emp_notsheet/$', views.EmployeeNoSheet, name='emp-no-sheets'),
    url(r'^emp_notfinished/$', views.EmpnotFinished, name='emp-not-finished'),
    # url(r'^sheet/(?P<empid>\d+)/update/$', views.EditSheet, name='edit-sheet'),
    url(r'^sheet/(?P<empid>\d+)/update/$', views.UpdateSheet, name='update-sheet'),
    url(r'^sheet/(?P<empid>\d+)/details/$', views.DetailseSheet, name='detials-sheet'),
    url(r'^sheet/(?P<empid>\d+)/show/$', views.EmpSheet, name='emp-sheet'),
    url(r'^add_project/$', views.AddProject, name='add-project'),
    url(r'^project_list/$', views.ProjectList, name='project-list'),
    url(r'^project_detail/(?P<pk>\d+)$', views.ProjectDetail, name='project-detail'),
    url(r'^project_edit/(?P<pk>\d+)$', views.ProjectEdit, name='project-edit'),
    url(r'^project_delete/(?P<pk>\d+)$', views.ProjectDelete, name='project-delete'),
    url(r'^project_task/(?P<pk>\d+)$', views.ProjectTask, name='project-task'),
    url(r'^project_task_detail/(?P<pk>\d+)$', views.ProjectTaskDetail, name='project-task-detail'),
    url(r'^project_team/(?P<pk>\d+)$', views.ProjectTeam, name='project-team'),
    url(r'^task_update_start/(?P<pk>\d+)$', views.updateStartDate, name='task-update-start'),
    url(r'^update_finish_task/(?P<pk>\d+)$',views.updateTaskFinish, name='update-finish-task'),
    url(r'^update_close_task/(?P<pk>\d+)$',views.updateTaskClose, name='update-close-task'),
    # url(r'^ProjectMember/$', ProjectMembersListView.as_view(), name='ProjectMember-list'),
    url(r'^.*\.html', views.gentella_html, name='gentella'),
    url(r'^auth/(?P<email>.*)/(?P<signature>.*)/(?P<time>.*)/$', views.loginfromdrupal, name='loginfromdrupal'),
    # Delegations
    url(r'^add_delegation/$',views.adddelegation, name='add-delegation'),
    url(r'^delegation/(?P<pk>\d+)/edit/$', views.editdelegation, name='edit-delegation'),
    url(r'^delegation/$',views.delegation, name='delegation'),
    url(r'^my_delegation/$',views.mydelegation, name='my-delegation'),
    # End Delegations

    url(r'^export/xls/$', views.export_users_xls, name='export_users_xls'),
    url(r'^export/xls/empnosheet$', views.export_empnosheet_xls, name='export_empnosheet_xls'),
    url(r'^export/xls/depts$', views.export_department_xls, name='export_departmen_xls'),
    url(r'^export/xls/deptsnosheet$', views.export_departmentnosheet_xls, name='export_departmennosheet_xls'),

]

ram/urls.py
from django.conf.urls import url ,include
from ram import views
from project.views import loginfromdrupal
from project.forms import BootstrapAuthenticationForm
from datetime import datetime
# from project.views import ProjectMembersListView
#application namespace
app_name = 'ramadan'

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.
    # The home page
    url(r'^$', views.index, name='index'),
    url(r'^quiz/$', views.quiz, name='quiz'),
    url(r'^quiz/(?P<period>\d+)/$', views.quiz_period, name='quiz-period'),
    url(r'^resulte/$', views.resulte, name='resulte'),
    url(r'^levels/$', views.levels, name='levels'),
    url(r'^employee-data/$', views.EmployeeDataView, name='employee-data'),
    url(r'^accounts/logout/$', views.logout, name='logout'),
    url(r'^conditions/$', views.conditions, name='conditions'),
    url(r'^auth/(?P<email>.*)/(?P<signature>.*)/(?P<time>.*)/$', loginfromdrupal, name='loginfromdrupal'),
    url(r'^accounts/login/$',
        views.myuser,
        {
            'template_name': 'ram/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^i18n/', include('django.conf.urls.i18n')),

]

tms/urls.py
from django.conf.urls import include, url
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from project import views
import project.forms
import project.views
from datetime import datetime
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.auth.views import logout

admin.site.site_header = _('Task Management System cp')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # app/ -> Genetelella UI and resources
    url(r'^project/', include('project.urls')), 
    url(r'^ram/', include('ram.urls')),
    url(r'^', include('project.urls')),
    url(r'^accounts/login/$',
        views.myuser,
        {
            'template_name': 'project/login.html',
            'authentication_form': project.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^su/', include('django_su.urls')),
    url(r'^accounts/logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^accounts/', include('django.contrib.auth.urls')),

]

project/models.py
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.db import models



class ApDeptTab(models.Model):
    dept_code = models.IntegerField(db_column='DEPT_CODE', blank=True, null=True)  # Field name made lowercase.
    dept_name = models.CharField(db_column='DEPT_NAME', max_length=86, blank=True, null=True)  # Field name made lowercase.
    branch_code = models.IntegerField(db_column='BRANCH_CODE', blank=True, null=True)  # Field name made lowercase.
    note = models.CharField(db_column='NOTE', max_length=21, blank=True, null=True)  # Field name made lowercase.
    manager_code = models.CharField(db_column='MANAGER_CODE', max_length=10, blank=True, null=True)  # Field name made lowercase.
    manager_title = models.CharField(db_column='MANAGER_TITLE', max_length=105, blank=True, null=True)  # Field name made lowercase.
    manager_ext = models.CharField(db_column='MANAGER_EXT', max_length=4, blank=True, null=True)  # Field name made lowercase.
    manager_phone = models.CharField(db_column='MANAGER_PHONE', max_length=9, blank=True, null=True)  # Field name made lowercase.
    resp_dept_code = models.CharField(db_column='RESP_DEPT_CODE', max_length=3, blank=True, null=True)  # Field name made lowercase.
    manager_level = models.CharField(db_column='MANAGER_LEVEL', max_length=7, blank=True, null=True)  # Field name made lowercase.
    authority_a = models.CharField(db_column='AUTHORITY_A', max_length=50, blank=True, null=True)  # Field name made lowercase.
    authority_b = models.CharField(db_column='AUTHORITY_B', max_length=50, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ap_dept_tab'

class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'

class AuthGroupPermissions(models.Model):
    group_id = models.IntegerField()
    permission_id = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group_id', 'permission_id'),)

class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type_id = models.IntegerField()
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type_id', 'codename'),)

class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'

class AuthUserGroups(models.Model):
    user_id = models.IntegerField()
    group_id = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user_id', 'group_id'),)

class AuthUserUserPermissions(models.Model):
    user_id = models.IntegerField()
    permission_id = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user_id', 'permission_id'),)

class Department(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    deptname = models.CharField(db_column='DeptName', max_length=200, blank=True, null=True)  # Field name made lowercase.
    managerid = models.CharField(db_column='ManagerId', max_length=45, blank=True, null=True)  # Field name made lowercase.
    deptcode = models.IntegerField(db_column='DeptCode',unique=True, blank=True, null=True)  # Field name made lowercase.
    managername = models.CharField(db_column='ManagerName', max_length=100, blank=True, null=True)  # Field name made lowercase.
    def __str__(self):
        return self.deptname
    class Meta:
        managed = False
        db_table = 'department'

class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type_id = models.IntegerField(blank=True, null=True)
    user_id = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'django_admin_log'

class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)

class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'

class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'

class Employee(models.Model):
		empid = models.CharField(db_column='EmpId', unique=True,max_length=50)  # Field name made lowercase.
		empname = models.CharField(db_column='EmpName', max_length=255, blank=True, null=True)  # Field name made lowercase.
		deptcode = models.CharField(db_column='DeptCode', max_length=45, blank=True, null=True)  # Field name made lowercase.
		deptname = models.CharField(db_column='DeptName', max_length=200, blank=True, null=True)  # Field name made lowercase.
		ismanager = models.IntegerField(db_column='IsManager', blank=True, null=True)  # Field name made lowercase.
		ext = models.CharField(db_column='Ext', max_length=45, blank=True, null=True)  # Field name made lowercase.
		mobile = models.CharField(db_column='Mobile', max_length=45, blank=True, null=True)  # Field name made lowercase.
		email = models.CharField(db_column='Email', max_length=100, blank=True, null=True)  # Field name made lowercase.
		jobtitle = models.CharField(db_column='JobTitle', max_length=200, blank=True, null=True)  # Field name made lowercase.
		managercode = models.BigIntegerField(db_column='ManagerCode', blank=True, null=True)  # Field name made lowercase.
		sexcode = models.CharField(db_column='SexCode', max_length=6, blank=True, null=True)  # Field name made lowercase.
		iscontract = models.IntegerField(db_column='IsContract', blank=True, null=True)  # Field name made lowercase.

		class Meta:
			managed = False
			db_table = 'employee'

class Project(models.Model):
    name = models.CharField(db_column='Name', max_length=250)  # Field name made lowercase.
    start = models.DateField(db_column='Start')  # Field name made lowercase.
    end = models.DateField(db_column='End')
    teamname = models.CharField(db_column='TeamName', max_length=100, blank=True, null=True)  # Field name made lowercase.
    desc = models.CharField(db_column='Desc', max_length=250)  # Field name made lowercase.
    createdby = models.CharField(db_column='CreatedBy', max_length=20, blank=True, null=True)  # Field name made lowercase.
    createddate = models.DateTimeField(db_column='CreatedDate', blank=True, null=True)  # Field name made lowercase.
    departementid = models.IntegerField(db_column='DepartementId', blank=True, null=True)  # Field name made lowercase.
    #statusid = models.IntegerField(db_column='StatusId', blank=True, null=True)  # Field name made lowercase.
    status = models.ForeignKey('ProjectStatus', on_delete=models.SET_NULL, null=True)
    openedby = models.CharField(db_column='OpenedBy', max_length=20, blank=True, null=True)  # Field name made lowercase.
    openeddate = models.DateTimeField(db_column='OpenedDate', blank=True, null=True)  # Field name made lowercase.
    closedby = models.CharField(db_column='ClosedBy', max_length=20, blank=True, null=True)  # Field name made lowercase.
    closeddate = models.DateTimeField(db_column='ClosedDate', blank=True, null=True)  # Field name made lowercase.
    canceledby = models.CharField(db_column='CanceledBy', max_length=20, blank=True, null=True)  # Field name made lowercase.
    canceleddate = models.DateTimeField(db_column='CanceledDate', blank=True, null=True)  # Field name made lowercase.
    deleted = models.IntegerField(db_column='Deleted', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'project'

class ProjectStatus(models.Model):
    name = models.IntegerField(db_column='Name')  # Field name made lowercase.
    name_ar = models.IntegerField(db_column='Name_Ar')  # Field name made lowercase.
    priority = models.IntegerField(db_column='Priority')  # Field priority made lowercase.
    isdefault = models.IntegerField(db_column='IsDefault')  # Field isdefault made lowercase.
    color = models.IntegerField(db_column='Color')  # Field color made lowercase.

    def __str__(self):
        return self.name_ar
        self.fields['verb'].empty_label = 'None'

    class Meta:
        managed = False
        db_table = 'project_status'

class Sheet(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    empid = models.ForeignKey('Employee', to_field='empid',db_column='EmpId', blank=True, null=True)  # Field name made lowercase.
    deptcode = models.ForeignKey('Department', to_field='deptcode', db_column='DeptCode', blank=True, null=True)  # Field name made lowercase.

ram/templates/ram/add_project.html
{% extends "project/base_site.html" %}
{% load i18n %}
{% block title %} {% trans "sheets list" %} {% endblock title %}

{% block stylesheets %}
{{ block.super }}
{% endblock stylesheets %}

{% block content %}


<div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
        <!--   <h3>{% trans "Ad Project" %} </h3> -->
        </div>
      </div>

      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
          <div class="x_title">
              <h3>{{ action_name }}</h3>  
              <ul class="nav navbar-right panel_toolbox">

              </ul>
              <div class="clearfix"></div>
            </div>


            <div class="x_content">

<!-- #to stop html validation put novalidate in form tag -->
<div class="col-md-8 col-sm-12   col-xs-12" >

              <form action="" method="post" class="form-horizontal form-label-left input_mask" novalidate enctype="multipart/form-data">

  {% csrf_token %}

                <div class="form-group">
              <div class=" col-md-12">
              {{form.name.label_tag}}
               {{form.name}}
               </div>
               </div>
               
               <div class="form-group">
              <div class=" col-md-4">
              {{form.start.label_tag}}
               {{form.start}}
                <span class="fa fa-calendar-o form-control-feedback left" style="margin-top:25px;" aria-hidden="true"></span>
               </div>
               
               <div class=" col-md-4">
                {{form.end.label_tag}}
               {{form.end}}
                <span class="fa fa-calendar-o form-control-feedback left" style="margin-top:25px;" aria-hidden="true"></span>
               </div>
               
                 <div class=" col-md-4">
                {{form.status.label_tag}}
               {{form.status}}
               </div>
               </div>
               
             <div class="form-group">
              <div class=" col-md-12">
              {{form.desc.label_tag}}
               {{form.desc}}
               </div>
               </div>

              
     <div class="form-group text-danger ">
     <div class="col-md-3"></div><div class="col-md-9 col-sm-12 col-xs-12">
    {{ form.name.errors }}
    {{ form.desc.errors }}
    {{ form.start.errors}}
    {{ form.end.errors  }}
   
    </div>
</div>
                <div class="ln_solid"></div>

                <div class="form-group">
                  <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-3">
                    <a href="{% url 'ns-project:project-list' %}" >  <button type="button" class="btn btn-primary">{{ _('Back')}}</button></a>
                    <!--  <button class="btn btn-primary" type="reset">{{_('Reset')}}</button>-->
                 <button type="submit" class="btn btn-success">{{_('Submit')}}</button>
                  </div>
                </div>

<!--  {{ form.as_p }} -->


   
    
    
    <!--  {{ form.start.label_tag }} -->

    


     
</form>


</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  
    <script>
  $('#single_cal_1').daterangepicker({
      singleDatePicker: true,
      singleClasses: "picker_1",
       locale: {
            format: 'YYYY-MM-DD'
        },
  }, function(start, end, label) {
     
  });
  
  $('#single_cal_2').daterangepicker({
      autoUpdateInput: true,
      singleDatePicker: true,
      singleClasses: "picker_1",
      locale: {
            format: 'YYYY-MM-DD',
            language: 'ar-EG',
        },
  }, function(start, end, label) {
    
  });
  </script>
  
{% endblock javascripts %}

ram/templates/ram/fixed_footer.html
{% extends "project/base_site.html" %}

{% block title %} Fixed Footer {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <!-- jQuery custom content scroller -->
  <link href="/static/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet"/>
{% endblock stylesheets %}

{% block body_class %}nav-md footer_fixed{% endblock body_class %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Fixed Footer <small> Just add class <strong>footer_fixed</strong></small></h3>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- jQuery custom content scroller -->
  <script src="/static/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
{% endblock javascripts %}

ram/templates/ram/fixed_sidebar.html
{% extends "project/base_site.html" %}

{% block title %} Fixed Sidebar {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <!-- jQuery custom content scroller -->
  <link href="/static/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet"/>
{% endblock stylesheets %}

{% block sidebar_class %}nav-md menu_fixed{% endblock sidebar_class %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Fixed Sidebar <small> Just add class <strong>menu_fixed</strong></small></h3>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- jQuery custom content scroller -->
  <script src="/static/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
{% endblock javascripts %}

ram/templates/ram/project_delete.html
{% extends "project/base_site.html" %}
{% load i18n %}
{% block title %} Plain Page {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
{% get_current_language as LANGUAGE_CODE %}
    <div class="right_col" role="main">
      <div class="">
        <div class="page-title">
          <div class="title_left">
            <h3></h3>
          </div>

          <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-default" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h3>{{ _('delete project confirmation') }} </h3>
           
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
              
              <div class="col-md-3 col-sm-3 col-xs-12">

                      <section class="panel">

                        
                        <div class="panel-body">
                          <h3 class="green"><i class="fa fa-paint-brush"></i> {{p.name}}</h3>

                          <p>{{p.desc}}</p>
                          <br>

                          <div class="project_detail">

                            <p class="title">{{_('Created By')}}</p>
                            <p>{{emp_obj.empname}}</p>
                            <p class="title">{{_('Created Date')}}</p>
                            <p>{{p.createddate}}</p>
                            <p class="title">{{ _('Status')}}</p>
                            <p>
                             {% if LANGUAGE_CODE == 'ar' %}
                      {{ p.status.name_ar  }}
                      {% else %}
                      {{ p.status.name  }}
                      {% endif %}
                             </p>
                          </div>

                          <br>
                          <h5>{{_('Attachments')}}</h5>
                          <ul class="list-unstyled project_files">
                            <li><a href=""><i class="fa fa-file-word-o"></i> Functional-requirements.docx</a>
                            </li>
                            <li><a href=""><i class="fa fa-file-pdf-o"></i> UAT.pdf</a>
                            </li>
                            <li><a href=""><i class="fa fa-mail-forward"></i> Email-from-flatbal.mln</a>
                            </li>
                            <li><a href=""><i class="fa fa-picture-o"></i> Logo.png</a>
                            </li>
                            <li><a href=""><i class="fa fa-file-word-o"></i> Contract-10_12_2014.docx</a>
                            </li>
                          </ul>
                          <br>

               
                        </div>

                      </section>
           <div class="text-center mtop20">
                            <form  action="" method="post" class="form-horizontal form-label-left input_mask" >
                 {% csrf_token %}
                <a href="{% url 'ns-project:project-list' %}" >  <button type="button" class="btn btn-primary">{{ _('Back')}}</button></a>
                   <button type="submit" class="btn btn-danger">{{_('Delete')}}</button>
               </form>
                          </div>
                    </div>
              
              
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

ram/templates/ram/sidebar.html
{% load i18n %}
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">

    <a href="{% url 'ns-project:index' %}" class="site_title"> <img src="/static/images/stats_logo.png" alt="..." class="img-rounded  profile_img" style="width:50px;">  <span>{{ _("Task Management") }} </span></a>
  </div>
  <div class="clearfix"></div>
  <!-- menu profile quick info -->
  <div class="profile clearfix">
    <div class="profile_info">
  {% if user.is_authenticated %}
      {% if 'EmpName' in request.session %}
      <h2>  {{ request.session.EmpName }}</h2>
      <span>  {{ request.session.JobTitle }}</span>
      <br>
      <span>  {{ request.session.DeptName }}</span>
        {# {{ mail }}#}
        {% endif %}
        {% endif %}
    </div>
  </div>
  <!-- /menu profile quick info -->
  <br />
  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <ul class="nav side-menu">
           <li><a href="/ram/employee-data"><i class="fa fa-list"></i> {% trans "Employee Data" %} <span class="fa"></span></a>  </li>
           <li><a href="/ram/levels"><i class="fa fa-list"></i> {% trans "Levels" %} <span class="fa"></span></a>  </li>
      </ul>
    </div></div>

  <!-- /sidebar menu -->


</div>