project/urls.py
from django.conf.urls import url ,include
from project import views
from rest_framework import routers

# from project.views import ProjectMembersListView
#application namespace
app_name = 'ns-project'



urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.

    # The home page
    url(r'^$', views.index, name='index'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^add-sheet/$', views.AddSheet, name='add-sheet'),
    # test rest api
    url(r'^rest-api/$', views.RestApi, name='rest-api'),
    url(r'^api-sheets/(?P<status>.+)/(?P<empid>.+)/$', views.SheetsStatusViewSet.as_view(), name='user'),
    ###
    url(r'^sheet/(?P<pk>\d+)/edit/$', views.EditSheet, name='edit-sheet'),
    url(r'^sheet/(?P<pk>\d+)/submit/$', views.SubmitSheet, name='submit-sheet'),
    url(r'^sheet/(?P<pk>\d+)/change/$', views.ChangeStatus, name='change-status'),
    url(r'^my_sheet/$', views.MySheet, name='my-sheet'),
    # url(r'^all_sheets/$', views.ManagerPage, name='all-sheets'),
    url(r'^all_employees_sheets/$', views.AllSheets, name='emps-sheets'),
    url(r'^all_dept_sheet/$', views.AllDept, name='dept-sheets'),
    url(r'^all_dept_sheets/$', views.AllDepts, name='department-sheets'),
    url(r'^dept_no_sheets/$', views.DeptsnoSheets, name='department-nosheets'),
    #url(r'^all_emp/$', views.IsManager, name='all-emp'),
    url(r'^sheet/(?P<deptcode>\d+)/dept/$', views.DeptSheet, name='dept-sheet'),
    # Employees does'nt have task
    url(r'^emp_notsheet/$', views.EmployeeNoSheet, name='emp-no-sheets'),
    url(r'^emp_notfinished/$', views.EmpnotFinished, name='emp-not-finished'),
    # url(r'^sheet/(?P<empid>\d+)/update/$', views.EditSheet, name='edit-sheet'),
    url(r'^sheet/(?P<empid>\d+)/update/$', views.UpdateSheet, name='update-sheet'),
    url(r'^sheet/(?P<empid>\d+)/details/$', views.DetailseSheet, name='detials-sheet'),
    url(r'^sheet/(?P<empid>\d+)/show/$', views.EmpSheet, name='emp-sheet'),
    url(r'^add_project/$', views.AddProject, name='add-project'),
    url(r'^project_list/$', views.ProjectList, name='project-list'),
    url(r'^project_detail/(?P<pk>\d+)$', views.ProjectDetail, name='project-detail'),
    url(r'^project_edit/(?P<pk>\d+)$', views.ProjectEdit, name='project-edit'),
    url(r'^project_delete/(?P<pk>\d+)$', views.ProjectDelete, name='project-delete'),
    url(r'^project_task/(?P<pk>\d+)$', views.ProjectTask, name='project-task'),
    url(r'^project_task_detail/(?P<pk>\d+)$', views.ProjectTaskDetail, name='project-task-detail'),
    url(r'^project_team/(?P<pk>\d+)$', views.ProjectTeam, name='project-team'),
    url(r'^task_update_start/(?P<pk>\d+)$', views.updateStartDate, name='task-update-start'),
    url(r'^update_finish_task/(?P<pk>\d+)$',views.updateTaskFinish, name='update-finish-task'),
    url(r'^update_close_task/(?P<pk>\d+)$',views.updateTaskClose, name='update-close-task'),
    # url(r'^ProjectMember/$', ProjectMembersListView.as_view(), name='ProjectMember-list'),
    url(r'^.*\.html', views.gentella_html, name='gentella'),
    url(r'^auth/(?P<email>.*)/(?P<signature>.*)/(?P<time>.*)/$', views.loginfromdrupal, name='loginfromdrupal'),
    # Delegations
    url(r'^add_delegation/$',views.adddelegation, name='add-delegation'),
    url(r'^delegation/(?P<pk>\d+)/edit/$', views.editdelegation, name='edit-delegation'),
    url(r'^delegation/$',views.delegation, name='delegation'),
    url(r'^my_delegation/$',views.mydelegation, name='my-delegation'),
    # End Delegations

    url(r'^export/xls/$', views.export_users_xls, name='export_users_xls'),
    url(r'^export/xls/empnosheet$', views.export_empnosheet_xls, name='export_empnosheet_xls'),
    url(r'^export/xls/depts$', views.export_department_xls, name='export_departmen_xls'),
    url(r'^export/xls/deptsnosheet$', views.export_departmentnosheet_xls, name='export_departmennosheet_xls'),

]

ram/urls.py
from django.conf.urls import url ,include
from ram import views
from project.views import loginfromdrupal
from project.forms import BootstrapAuthenticationForm
from datetime import datetime
# from project.views import ProjectMembersListView
#application namespace
app_name = 'ramadan'

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.
    # The home page
    url(r'^$', views.index, name='index'),
    url(r'^quiz/$', views.quiz, name='quiz'),
    url(r'^quiz/(?P<period>\d+)/$', views.quiz_period, name='quiz-period'),
    url(r'^resulte/$', views.resulte, name='resulte'),
    url(r'^levels/$', views.levels, name='levels'),
    url(r'^employee-data/$', views.EmployeeDataView, name='employee-data'),
    url(r'^accounts/logout/$', views.logout, name='logout'),
    url(r'^conditions/$', views.conditions, name='conditions'),
    url(r'^auth/(?P<email>.*)/(?P<signature>.*)/(?P<time>.*)/$', loginfromdrupal, name='loginfromdrupal'),
    url(r'^accounts/login/$',
        views.myuser,
        {
            'template_name': 'ram/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^i18n/', include('django.conf.urls.i18n')),

]

tms/urls.py
from django.conf.urls import include, url
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from project import views
import project.forms
import project.views
from datetime import datetime
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.auth.views import logout

admin.site.site_header = _('Task Management System cp')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # app/ -> Genetelella UI and resources
    url(r'^project/', include('project.urls')), 
    url(r'^ram/', include('ram.urls')),
    url(r'^', include('project.urls')),
    url(r'^accounts/login/$',
        views.myuser,
        {
            'template_name': 'project/login.html',
            'authentication_form': project.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^su/', include('django_su.urls')),
    url(r'^accounts/logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^accounts/', include('django.contrib.auth.urls')),

]

project/views.py
from django.shortcuts import render, render_to_response ,get_object_or_404,redirect
from django.template import loader
from django.http import HttpResponse ,HttpResponseRedirect,Http404 ,HttpResponseForbidden
from .models import *
from .forms import *
from django.contrib.auth.views import *
from django.utils.translation import ugettext as _
from django.forms import formset_factory
from django.forms import BaseModelFormSet
from datetime import datetime , timedelta
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth.models import Group , User
from django.contrib.auth.decorators import permission_required
from django.views.generic import UpdateView, ListView
from .filters import SheetFilter
from django.template.loader import  render_to_string
from django.http import JsonResponse
from django.views.generic.list import ListView
from django.core.urlresolvers import resolve
from django.core.cache import cache
from rest_framework import viewsets , generics
from rest_framework.response import Response
from rest_framework.views import APIView
from django.contrib.sites import requests

from .serializers import UserSerializer, GroupSerializer



class SheetsStatusViewSet(APIView):
    """
    API endpoint that allows users to be viewed or edited.
    """
    def get(self, request, status,empid):
        """
        Get current week range start week is sunday end day is saturday
        """
        date = datetime.now()
        year, week, dow = date.isocalendar()
        if dow == 7:
            start_date = date
        else:
            start_date = date - timedelta(dow)
        end_date = start_date + timedelta(6)
        """ End current week """
        sheet = Sheet.objects.filter(empid=empid)
        if status == 'inprogress':
            sheet = sheet.filter(Q(status=1))
        elif status == 'notfinish':
            sheet = sheet.filter(Q(status=3))
        queryset = sheet.filter(
            Q(taskdate__gte=end_date, createddate__lte=start_date) |
            Q(taskdate__lte=end_date, taskdate__gte=start_date) |
            Q(createddate__lte=end_date, createddate__gte=start_date)
        )

        serializer_class = UserSerializer(queryset,many=True)
        return Response(serializer_class.data)


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer


def RestApi(request):
    import urllib.request, json
    empid = '1028645107'
    with urllib.request.urlopen("http://127.0.0.1:8000/project/api-sheets/inprogress/" + empid + '/') as url:
        data = json.loads(url.read())
    context = {'user':data}
    return render(request, 'project/rest-api.html', context)


class BaseSheetFormSet(BaseModelFormSet):
    def clean(self):
        if any(self.errors):
            return
        taskdesc = []
        for form in self.forms:
            taskdescs = form.cleaned_data['taskdescs']
            if taskdescs in titles:
                raise forms.ValidationError("Articles in a set must have distinct titles.")
            titles.append(title)


def loginfromdrupal(request, email,signature,time):
    from django.urls import resolve
    current_url = resolve(request.path_info).namespaces
    request.session['current_url'] = None
    if current_url:
        request.session['current_url'] = current_url
    print ("current url" ,current_url)
    from django.contrib.auth import login
    import getpass
    import datetime
    """ Email function """
    def decrypted(text):
        from Crypto.Cipher import AES
        from Crypto.Cipher import DES
        import base64
        #AES.key_size=128
        key = b"5E712B225B5148E9"
        iv = b"55FE52A86C3ABWED"
        crypt_object = AES.new(key=key,mode=AES.MODE_CBC,IV=iv)
        original = text
        plain = original.replace('-', "/")
        decoded=base64.b64decode(plain) # your ecrypted and encoded text goes here
        decrypted=crypt_object.decrypt(decoded)
        decrypted = decrypted.decode("utf-8")
        return decrypted
    """" return mail"""
    mail = decrypted(email)
    """ return ip """
    ip = 1
    ip = decrypted(signature)
    """ return time """
    time = decrypted(time)

    now = datetime.datetime.now()
    now_plus_10 = now + datetime.timedelta(minutes = 1)
    time_now = now.strftime('%H:%M')
    date_after_minute = now_plus_10.strftime('%H:%M')

    """ Current ip """
    current_ip = request.META.get('REMOTE_ADDR')
    """" Get url from"""
    URL = request.META.get('HTTP_REFERER')
    print (URL)
    referer = None
    if URL:
        referer= URL.split("/")[2]
    if referer == 'portal.stats.gov.sa':
        if current_ip in ip:
        #     if time == time_now or time == date_after_minute:
            username = mail
            try:
                user = User.objects.get(username=username)
                #manually set the backend attribute
                user.backend = 'django.contrib.auth.backends.ModelBackend'
                login(request, user)
            except User.DoesNotExist:
                from django_auth_ldap.backend import LDAPBackend
                ldap_backend = LDAPBackend()
                ldap_backend.populate_user(username)
                # return HttpResponseRedirect(reverse('login'))
            try:
                user = User.objects.get(username=username)
                #manually set the backend attribute
                user.backend = 'django.contrib.auth.backends.ModelBackend'
                login(request, user)
            except User.DoesNotExist:
                if 'ramadan' in current_url:
                    return HttpResponseRedirect(reverse('ramadan:login'))
                return HttpResponseRedirect(reverse('login'))
            if request.user.is_authenticated():
                email = request.user.email
                emp = Employee.objects.filter(email= email)
            # Get all data filtered by user email and set in session
                for data in emp:
                    request.session['EmpID'] = data.empid
                    request.session['EmpName'] = data.empname
                    request.session['DeptName'] = data.deptname
                    request.session['Mobile'] = data.mobile
                    request.session['DeptCode'] = data.deptcode
                    request.session['JobTitle'] = data.jobtitle
                    request.session['IsManager'] = data.ismanager
                if emp:
                    if data.ismanager == 1:
                        g = Group.objects.get(name='ismanager')
                        g.user_set.add(request.user.id)
                    else:
                        g = Group.objects.get(name='employee')
                        g.user_set.add(request.user.id)
                # if not emp:
                #     g = Group.objects.get(name='employee')
                #     g.user_set.add(request.user.id)
            else:
                return HttpResponseRedirect(reverse('login'))
    else:
        if 'ramadan' in current_url:
            return HttpResponseRedirect(reverse('ramadan:login'))

        return HttpResponseRedirect(reverse('login'))

    logged = request.COOKIES.get('logged_in_status')
    context = {'logged':logged, "mail":mail,"ip":ip,"time1":time,"URL":referer}
    template = loader.get_template('project/index.html')
    return HttpResponseRedirect(reverse('ns-project:index'))

def myuser(request, *args, **kwargs):
    if request.method == "POST":
        form = BootstrapAuthenticationForm(request, data=request.POST)
        emp = None
        if form.is_valid():
          auth_login(request, form.get_user())
            # email = None
        if request.user.is_authenticated():
            email = request.user.email
            emp = Employee.objects.filter(email= email)
        # Get all data filtered by user email and set in session
            for data in emp:
                request.session['EmpID'] = data.empid
                request.session['EmpName'] = data.empname
                request.session['DeptName'] = data.deptname
                request.session['Mobile'] = data.mobile
                request.session['DeptCode'] = data.deptcode
                request.session['JobTitle'] = data.jobtitle
                request.session['IsManager'] = data.ismanager
            if emp:
                if data.ismanager == 1:
                    g = Group.objects.get(name='ismanager')
                    g.user_set.add(request.user.id)
                else:
                    g = Group.objects.get(name='employee')
                    g.user_set.add(request.user.id)
            # if not emp:
            #     g = Group.objects.get(name='employee')
            #     g.user_set.add(request.user.id)

        else:
            return login(request, *args, **kwargs)
    return login(request, *args, **kwargs)

@login_required
def index(request):
    current_url = request.session.get('current_url')
    print ('session', current_url)
    if current_url:
        if 'ramadan' in current_url:
            print('ramadan login')
            return HttpResponseRedirect(reverse('ramadan:index'))
    if request.user.is_authenticated():
        deptcode= request.session.get('DeptCode')
    if request.session.get('IsManager'):
        return HttpResponseRedirect(reverse('ns-project:dept-sheet' ,kwargs={'deptcode': deptcode}))
    else:
        return HttpResponseRedirect(reverse('ns-project:my-sheet'))
    if request.user.is_authenticated():
        emp = get_object_or_404(Employee, empid = request.session.get('empid'))
    if emp.ismanager == 1:
        template = loader.get_template('project/index.html')
        return HttpResponse(template.render(context, request))
    else:

project/templates/project/base_site.html
<!DOCTYPE html>
<html lang="ar-EG">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      {% endblock meta %}
      <title>نظام إدارة المهام-الهيئة العامة للإحصاء| {% block title %}{% endblock %}</title>
      {% block stylesheets %}
        <!-- Bootstrap -->
        <style>
        @font-face { font-family: 'neo';
         src: url('/static/fonts/neo/NeoSansArabic.eot');
         src: url('/static/fonts/neo/NeoSansArabic.eot?#iefix') format('embedded-opentype'),
         url('/static/fonts/neo/NeoSansArabic.woff') format('woff'),
         url('/static/fonts/neo/NeoSansArabic.ttf') format('truetype'),
         url('/static/fonts/neo/NeoSansArabic.svg#ge_neofont') format('svg'); font-style: normal; }

        </style>
        <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
      <link href="/static/vendors/bootstrap/dist/css/bootstrap-rtl.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="/static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="/static/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
        <!-- iCheck -->
        <link href="/static/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="/static/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
        <!-- JQVMap -->
        <link href="/static/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="/static/build/css/custom_rtl.css" rel="stylesheet">
    {% endblock head %}
  </head>
<body class="{% block body_class %}nav-md {% endblock body_class %}">

    {% block body %}

      <div class="container body">
        <div class="main_container">
          {% block sidebar %}
            <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
              {% include "project/sidebar.html" %}
            </div>
          {% endblock sidebar %}

          {% block top_navigation %}


            <div class="top_nav">
              {% include "project/top_navigation.html" %}
            </div>
          {% endblock top_navigation %}

          {% block content %}


          {% include 'project/messages.html' %}
            <!-- {{ content }} -->


          {% endblock content %}

          {% block footer %}
            <footer>
              {% include "project/footer.html" %}
            </footer>
          {% endblock footer %}
        </div>
      </div>
      {% block javascripts %}
        <!-- jQuery -->
        <script src="/static/vendors/jquery/dist/jquery.min.js"></script>
        <script src="/static/vendors/jquery/dist/jquery-ui.js"></script>
        <!-- Bootstrap -->
        <script src="/static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="/static/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="/static/vendors/nprogress/nprogress.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="/static/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="/static/vendors/iCheck/icheck.min.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="/static/vendors/moment/min/moment.min.js"></script>
        <script src="/static/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="/static/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js"></script>
        <script src="/static/vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
        <script src="/static/vendors/google-code-prettify/src/prettify.js"></script>
        <!-- jQuery Tags Input -->
        <script src="/static/vendors/jquery.tagsinput/src/jquery.tagsinput.js"></script>
        <!-- Switchery -->
        <script src="/static/vendors/switchery/dist/switchery.min.js"></script>
        <!-- Select2 -->
        <script src="/static/vendors/select2/dist/js/select2.full.min.js"></script>
        <!-- Parsley -->
        <script src="/static/vendors/parsleyjs/dist/parsley.min.js"></script>
        <!-- Autosize -->
        <script src="/static/vendors/autosize/dist/autosize.min.js"></script>
        <!-- jQuery autocomplete -->
        <script src="/static/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
        <!-- starrr -->
        <script src="/static/vendors/starrr/dist/starrr.js"></script>

      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="/static/build/js/jquery.datepick-ar.js"></script>
      <script src="/static/build/js/custom.js"></script>

    {% endblock body %}
  </body>
</html>

project/templates/project/login.html
{% extends "project/base_site.html" %}

{% block title %} Login {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <!-- Animate.css -->
  <link href="/static/vendors/animate.css/animate.min.css" rel="stylesheet">

  <style>
body, html {
    height: 100%;
    margin: 0;
}

body {
   /*background: #092756 !important;
    /* The image used */
    background-image: url("http://www.dailygalaxy.com/.a/6a00d8341bf7f753ef01b7c86b22a2970b-pi") !important;

    /* Full height */
    height: 100% !important;

    /* Center and scale the image nicely */
    background-position: center !important;
    background-repeat: no-repeat !important;
    background-size: cover !important;



}
</style>

{% endblock stylesheets %}

{% block body_class %}login{% endblock body_class %}

{% block body %}

<div class="bg"></div>
  <div>
    <a class="hiddenanchor" id="signup"></a>
    <a class="hiddenanchor" id="signin"></a>

    <div class="login_wrapper">
      <div class="animate form login_form">
        <section class="login_content">

  <img src="/static/images/stats_logo.png" alt="..." class="img-rounded profile_img">
          <form action="." method="post" class="form-horizontal">
            {% csrf_token %}

            <h1>{{ _('Login Form')}}</h1>
            {% if form.errors %}
            <div class="alert alert-danger">
              <p class="validation-summary-errors">{{ _('Please enter a correct user name and password.') }}</p>
            </div>
            {% endif %}
            <div>
               {{ form.username }}
            </div>
            <div>
               {{ form.password }}
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="hidden" name="next" value="{{ next }}" />
                    <input type="submit" value="{{_('Log in')}}" class="btn btn-default" />
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="separator">


              <div class="clearfix"></div>
              <br />

              <div>
               <!-- <h1> <i class="fa fa-paw"></i> </h1> -->
               <br><br>
                <p>©2017 نظام ادارة المهام - الهيئة العامة للإحصاء</p>
              </div>
            </div>
          </form>
        </section>
      </div>
      {# sign up #}
      <div id="register" class="animate form registration_form">
        <section class="login_content">
          <form>
            <h1>Create Account</h1>
            <div>
              <input type="text" class="form-control" placeholder="Username" required="" />
            </div>
            <div>
              <input type="email" class="form-control" placeholder="Email" required="" />
            </div>
            <div>
              <input type="password" class="form-control" placeholder="Password" required="" />
            </div>
            <div>
              <a class="btn btn-default submit" href="index.html">Submit</a>
            </div>
            <div class="clearfix"></div>
            <div class="separator">
              <p class="change_link">Already a member ?
                <a href="#signin" class="to_register"> Log in </a>
              </p>

              <div class="clearfix"></div>
              <br />

              <div>
                <h1><i class="fa fa-paw"></i> Gentelella Alela!</h1>
                <p>©2016 All Rights Reserved. Gentelella Alela! is a Bootstrap 3 template. Privacy and Terms</p>
              </div>
            </div>
          </form>
        </section>
      </div>
    </div>
  </div>
{% endblock body %}

project/templates/project/rest-api.html
{% extends "project/base_site.html" %}
{% load i18n %}
{% block title %} {% trans "Projects" %} {% endblock title %}

{% block stylesheets %}
{{ block.super }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>{% trans "Rest api" %} </h3>
        </div>
        <div class="title_right">
        <!--  <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="{{_('Search for')}}...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">{% trans "Go"  %}!</button>
              </span>
            </div>
          </div> -->
        </div>
      </div>

      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
              <div class="x_title">

              <div class="clearfix"></div>
            </div>
            <div class="x_content">

{% for item in user %}
    {{ item.taskdesc }}<br>
{%  endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

project/templates/project/sidebar.html
{% load i18n %}
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">

    <a href="{% url 'ns-project:index' %}" class="site_title"> <img src="/static/images/stats_logo.png" alt="..." class="img-rounded  profile_img" style="width:50px;">  <span>{{ _("Task Management") }} </span></a>
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">
    <div class="profile_info">
  {% if user.is_authenticated %}
      {% if 'EmpName' in request.session %}
      <h2>  {{ request.session.EmpName }}</h2>
      <span>  {{ request.session.JobTitle }}</span>
      <br>
      <span>  {{ request.session.DeptName }}</span>
        {# {{ mail }}#}
        {% endif %}
        {% endif %}

    </div>
  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <ul class="nav side-menu">
           <li><a href="{% url 'ns-project:my-sheet' %}"><i class="fa fa-list"></i> {% trans "My To Do List" %} <span class="fa"></span></a>  </li>
           {% load user_group %}
           {% if request.user|has_group:"ismanager" or request.session.have_auth %}
           <li><a><i class="fa fa-hand-o-left"></i> {% trans "Delegations" %} <span class="fa fa-chevron-down"></span></a>
         <ul class="nav child_menu">
           {% if request.user|has_group:"ismanager" %}
           <li><a href="{% url 'ns-project:delegation'%}">{{_('Manage Delegation')}}</a></li>
           {%endif%}
           <li><a href="{% url 'ns-project:my-delegation'%}">{{_('Department Delegation')}}</a></li>
         </ul>
       </li>
           {%endif%}
           {% if request.user|has_group:"ismanager" %}
           <li><a href=" /sheet/{{request.session.DeptCode}}/dept "><i class="fa fa-pencil-square-o"></i> {% trans "manage all sheets" %} <span class="fa"></span></a>  </li>

            <li><a><i class="fa fa-file-text-o"></i> {% trans "Reports" %} <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'ns-project:department-sheets'%}">{{_('All Department')}}</a></li>
             {% if request.user|has_group:"supermanager" %}
            <li><a href="{% url 'ns-project:emp-no-sheets'%}">{{_('Employess not have tasks')}}</a></li>
            <li><a href="{% url 'ns-project:emp-not-finished'%}">{{_('Employess not finished tasks')}}</a></li>
             {%endif%}
          </ul>
        </li>
           {% endif %}
      </ul>
    </div></div>

  <!-- /sidebar menu -->


</div>